### ISSUE TITLE
QOL Suggestion

### ISSUE THREAD

**Issue by ASPJulien** [Jackamikaz/BSAutoRequest#1]
QOL Suggestion:
Lock the ability to resize the window

**Comment by Jackamilio** [comment]
It's already the case! Maybe it's on my machine only? Or you have an old version of the .exe?
I sneakily uploaded a new one the first day without making it a new release so maybe that's why?
Try downloading it again and tell me if you can resize the window

**Comment by ASPJulien** [comment]
Sorry, I can't find the exe that you uploaded, and btw, the source code isn't building, there are missings files
![image](https://user-images.githubusercontent.com/49618271/111062190-be2da780-84a7-11eb-99f2-3e2951e9987e.png)

**Comment by Jackamilio** [comment]
The .exe I'm talking about is the one provided in releases.

About building, I should update the readme to indicate the dependencies I'm using. I use the nana gui library, I don't provide it, you have to build it yourself then configure the project to link to it and find the header files. http://nanapro.org/en-us/

**Comment by ASPJulien** [comment]
Yep, so it works now, you should maybe remove the ability to click on the resize button even if we can't use it
